// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKDRG1s3cOx8vAWM_nZSs-jl1rGHjRpI',
    appId: '1:549030954690:web:3615ba2b01c5e9ce3b1d5b',
    messagingSenderId: '549030954690',
    projectId: 'sosmed-app-1620f',
    authDomain: 'sosmed-app-1620f.firebaseapp.com',
    storageBucket: 'sosmed-app-1620f.firebasestorage.app',
    measurementId: 'G-550SZ67MFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KzsTY3OjRyYueRA1s4U-eOY2aSPaMg4',
    appId: '1:549030954690:android:12d16633e46723fc3b1d5b',
    messagingSenderId: '549030954690',
    projectId: 'sosmed-app-1620f',
    storageBucket: 'sosmed-app-1620f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBPXTbONQXYeyy5UCNyT2N2BmCHfOagQ',
    appId: '1:549030954690:ios:5607985a34514d9c3b1d5b',
    messagingSenderId: '549030954690',
    projectId: 'sosmed-app-1620f',
    storageBucket: 'sosmed-app-1620f.firebasestorage.app',
    iosBundleId: 'com.example.miniSosmedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBPXTbONQXYeyy5UCNyT2N2BmCHfOagQ',
    appId: '1:549030954690:ios:5607985a34514d9c3b1d5b',
    messagingSenderId: '549030954690',
    projectId: 'sosmed-app-1620f',
    storageBucket: 'sosmed-app-1620f.firebasestorage.app',
    iosBundleId: 'com.example.miniSosmedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKDRG1s3cOx8vAWM_nZSs-jl1rGHjRpI',
    appId: '1:549030954690:web:632f5bd34a1868dc3b1d5b',
    messagingSenderId: '549030954690',
    projectId: 'sosmed-app-1620f',
    authDomain: 'sosmed-app-1620f.firebaseapp.com',
    storageBucket: 'sosmed-app-1620f.firebasestorage.app',
    measurementId: 'G-RLQDLRB6R5',
  );
}
